export const INIT_FILTER = 'INIT_FILTER';

export const SET_FILTER = 'SET_FILTER';
export const SET_FILTER_SUCCESS = 'SET_FILTER_SUCCESS';
export const SET_FILTER_FAIL = 'SET_FILTER_FAIL';

export const SET_SORTING = 'SET_SORTING';
export const SET_SORTING_SUCCESS = 'SET_SORTING_SUCCESS';
export const SET_SORTING_FAIL = 'SET_SORTING_FAIL';