export const SET_PHOTO = 'SET_PHOTO';
export const SET_PHOTO_SUCCESS = 'SET_PHOTO_SUCCESS';
export const SET_PHOTO_FAIL = 'SET_PHOTO_FAIL';

export const MERGE_PHOTO_DATA = 'MERGE_PHOTO_DATA';
export const MERGE_PHOTO_DATA_SUCCESS = 'MERGE_PHOTO_DATA_SUCCESS';
export const MERGE_PHOTO_DATA_FAIL = 'MERGE_PHOTO_DATA_FAIL';

export const UPDATE_PHOTO = 'UPDATE_PHOTO';