export const SIGNUP_FORM_RESET = 'SIGNUP_FORM_RESET';
export const SIGNUP_FORM_SET = 'SIGNUP_FORM_SET';
export const SIGNUP_SET_TYPE = 'SIGNUP_SET_TYPE';

export const CREATE_CUSTOMER = 'CREATE_CUSTOMER';
export const CREATE_CUSTOMER_SUCCESS = 'CREATE_CUSTOMER_SUCCESS';
export const CREATE_CUSTOMER_FAIL = 'CREATE_CUSTOMER_FAIL';