export const CREATE_USER = 'CREATE_USER';
export const CREATE_USER_SUCCESS = 'CREATE_USER_SUCCESS';
export const CREATE_USER_FAIL = 'CREATE_USER_FAIL';

export const SET_SIGNUP_MODAL = 'SET_SIGNUP_MODAL';
export const SET_USER_SUCCESS = 'SET_USER_SUCCESS';