export const SIGNUP_FORM_RESET = 'SIGNUP_FORM_RESET';
export const SIGNUP_FORM_SET = 'SIGNUP_FORM_SET';
export const SIGNUP_SET_TYPE = 'SIGNUP_SET_TYPE';

export const CREATE_USER = 'CREATE_USER';
export const CREATE_USER_SUCCESS = 'CREATE_USER_SUCCESS';
export const CREATE_USER_FAIL = 'CREATE_USER_FAIL';